name: pLeagueManager
version: 1.2.5
authors:
  - Neeonn
  - Maatijaa
depend:
  - LuckPerms
load: POSTWORLD
main: io.github.firerealms.pLeagueManager
commands:
  leaguemanager:
    description: Base command.
    aliases: [plm]
  timer:
    description: Timer command.
    aliases: [ts]
  result:
    description: Result command.
    aliases: [rs]
  2x4:
    description: 2x4 Result command.
  1x8:
    description: 1x8 Result command.
